travis:
  secure:
    BINSTAR_TOKEN: uTnVCntvsKmPcrpb389YbULx9mudPrJXw3QRYB2jKsXwgNcEnqhg98ATIbOx52531iCKv/CdNddyPj/EyxafkQPIRnZXDN5p2SZG0b6Q13eSjh+mZ4O7V96zVE5FoYCnAhSxVsu28jWKiSbp207rASxSOej7qdyI6uUI6RiogF9fBfR2BYEorjTefEDAf7/QcA5dKSb8mSVpXsvaLy/8zje+12druGcByu+2y58huqH0I0TeYf1etVt5jHTKYdAma1hY7QLrA7rETil05JMh2mkBn4eBDDL6dx5UaWYPp6p4MQ0cC5tYqn/G1jF7p15UlnWYjUIVHuTyPrpCuTPXVzxgW93n4f8iypggk+0Mx3iDMoMCA28G/MhbUeP5eVe//Y+o8mVPez4344fxGiaclHcirWIgpxK40CTnrfHCU1n9vNL0FGQVmnKZk1tUunPKYvtlnthYrZYTUFBvo3sd/HdYV84mgNqdUMNgJ4kjcGjt71KcticnECPmJjTyDMDQOXJ/oYfB/8ydJQjhdU3+CUmpantHPyGMknDVTFGVmLmCtkdMN6ha9FOAXxSEBZM/vrA1Nk9Vd0IoZ4kPfkfzuJVGwQE/PiJwbHB6uPFcfJiL7ZH8a7Tt0Ujyu2H3T8rn40KNnOLskAKFWOunco9sRJfqRefwvEQDh0rPfGbsG74=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
